let
    Источник = Excel.CurrentWorkbook(){[Name="РВ"]}[Content],
    #"Измененный тип" = Table.TransformColumnTypes(Источник,{{"№ п/п", Int64.Type}, {"Сотрудник", type any}, {"Должность", type any}, {"Ссостав работ", type any}, {"ФОТ", Int64.Type}, {"ОКЛАД", Int64.Type}, {"НАДБАВКА", Int64.Type}, {"Норма часов", Int64.Type}, {"Фактически отработанные часы", Int64.Type}, {"Часы отнесённые на проект", Int64.Type}, {"Трудоемкость", Int64.Type}, {"Основные начисления на проект", Int64.Type}, {"Расчётный % страховых взносов на проект", type number}, {"Плановые страховые взносы на проект", Int64.Type}, {"Основные начисления на проект с учётом согласованной ставки", Int64.Type}, {"Плановые страховые взносы на проект с учётом согласованной ставки", Int64.Type}, {"Фактический % страховых взносов", type number}, {"Фактические страховые взносы на проект", Int64.Type}, {"Год", Int64.Type}, {"План/Факт", type any}, {"% Страховых взносов функция", type any}, {"Месяц числом", Int64.Type}, {"Табельный номер", type any}, {"Сокращённое Ф.И.О.", type text}, {"Месяц прописью", type text}, {"Проект", type any}, {"МесяцГодович", type date}, {"ФИО Годович", type text}, {"ДолжностьЕщё", type any}, {"Премия", Int64.Type}, {"Начислено денег сотруднику за месяц", Int64.Type}, {"Начислено денег сотруднику за год", Int64.Type}, {"ФСС", type number}, {"ПФ", type number}, {"ФФОМС", type number}, {"Травматизм", type number}, {"Социальные отчисления", type any}}),
    #"Добавлен пользовательский объект" = Table.AddColumn(#"Измененный тип", "Пользовательский", each if Text.Contains([Сотрудник], "Январь") or 
        Text.Contains([Сотрудник], "Февраль") or 
        Text.Contains([Сотрудник], "Март") or 
        Text.Contains([Сотрудник], "Апрель") or 
        Text.Contains([Сотрудник], "Май") or 
        Text.Contains([Сотрудник], "Июнь") or 
        Text.Contains([Сотрудник], "Июль") or 
        Text.Contains([Сотрудник], "Август") or 
        Text.Contains([Сотрудник], "Сентябрь") or 
        Text.Contains([Сотрудник], "Октябрь") or 
        Text.Contains([Сотрудник], "Ноябрь") or 
        Text.Contains([Сотрудник], "Декабрь")
     then "" 
     else [Сотрудник]),
    #"Удаленные ошибки" = Table.RemoveRowsWithErrors(#"Добавлен пользовательский объект", {"Пользовательский"}),
    #"Удаленные дубликаты" = Table.Distinct(#"Удаленные ошибки", {"Пользовательский"}),
    #"Удаленные столбцы" = Table.RemoveColumns(#"Удаленные дубликаты",{"№ п/п", "Сотрудник", "Должность", "Ссостав работ", "ФОТ", "ОКЛАД", "НАДБАВКА", "Норма часов", "Фактически отработанные часы", "Часы отнесённые на проект", "Трудоемкость", "Основные начисления на проект", "Расчётный % страховых взносов на проект", "Плановые страховые взносы на проект", "Основные начисления на проект с учётом согласованной ставки", "Плановые страховые взносы на проект с учётом согласованной ставки", "Фактический % страховых взносов", "Фактические страховые взносы на проект", "Год", "План/Факт", "% Страховых взносов функция", "Месяц числом", "Табельный номер", "Сокращённое Ф.И.О.", "Месяц прописью", "Проект", "МесяцГодович", "ФИО Годович", "ДолжностьЕщё", "Премия", "Начислено денег сотруднику за месяц", "Начислено денег сотруднику за год", "ФСС", "ПФ", "ФФОМС", "Травматизм", "Социальные отчисления"}),
    #"Удалены пустые строки" = Table.SelectRows(#"Удаленные столбцы", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
in
    #"Удалены пустые строки"