let
    // Шаг 1: Получаем данные только из столбца "Сотрудник" и изменяем его тип на текст
    ИсходныеДанные = Excel.CurrentWorkbook(){[Name="РВ"]}[Content],
    Сотрудники = Table.SelectColumns(ИсходныеДанные, {"Сотрудник"}),
    СотрудникиТип = Table.TransformColumnTypes(Сотрудники, {{"Сотрудник", type text}}),

    // Шаг 2: Определяем список месяцев
    Месяцы = {"Январь", "Февраль", "Март", "Апрель", "Май", 
              "Июнь", "Июль", "Август", "Сентябрь", 
              "Октябрь", "Ноябрь", "Декабрь"},

    // Шаг 3: Фильтруем сотрудников, содержащих названия месяцев
    ФильтрованныеСотрудники = Table.SelectRows(СотрудникиТип, 
        each not List.AnyTrue(List.Transform(Месяцы, (месяц) => Text.Contains([Сотрудник], месяц)))),

    // Шаг 4: Удаляем строки, где [Сотрудник] равен "0"
    РезультатФильтрации = Table.SelectRows(ФильтрованныеСотрудники, each ([Сотрудник] <> "0")),
    #"Удалены пустые строки" = Table.SelectRows(РезультатФильтрации, each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Удаленные дубликаты" = Table.Distinct(#"Удалены пустые строки")
in
    #"Удаленные дубликаты"